### ISSUE TITLE
Test 

### ISSUE THREAD

**Issue by zouma45** [wassim404/DevZummenApp#1]
Test

**Comment by le7amdon** [comment]
l org.apache.http ma tsirlich l import mte3ou

**Comment by zouma45** [comment]
Lezmek tsob l git , sinon telecharger le projet  et l ouvrir directement avec android studio mouch mech yemchi dima

**Comment by le7amdon** [comment]
sayé sabitou l git

**Comment by mariemDHOUIB** [comment]
​
 Nouveau dossier (2).rar
https://drive.google.com/file/d/0B3T6sezRNfjjd2ZuZGw1YVJFZWc/view?usp=drive_web
​
https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=T-000-800-A
Cet
e-mail a été envoyé depuis un ordinateur protégé par Avast.
www.avast.com
https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=T-000-800-A
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2016-01-23 14:14 GMT+01:00 le7amdon notifications@github.com:
